INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika) VALUES ('Petar', 'Petrovic', 'pera', '$2a$10$WyGU0850Gt6l9niernBpb.58pCPz8XXEaI4qvOyj5rdEYIygCat/u', 'peracar@example.com', 'Izmisljenog Heroja 14', 'Novi Sad', '060 232 3232', 'ADMINISTRATOR');
INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika) VALUES ('Andrea', 'Sancic', 'andrea', '$2a$10$WyGU0850Gt6l9niernBpb.58pCPz8XXEaI4qvOyj5rdEYIygCat/u', 'andrea@example.com', 'Stevana Sremca 2/3', 'Novi Sad', '063 773 3832', 'ADMINISTRATOR');
INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika) VALUES ('Manja', 'Ilicic', 'manja', '$2a$10$WyGU0850Gt6l9niernBpb.58pCPz8XXEaI4qvOyj5rdEYIygCat/u', 'manjai@example.com', 'Bulevar Cara Lazara 13', 'Novi Sad', '064 442 4723', 'ADMINISTRATOR');
INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika) VALUES ('Sinisa', 'Marjanovic', 'sinisa', '$2a$10$WyGU0850Gt6l9niernBpb.58pCPz8XXEaI4qvOyj5rdEYIygCat/u', 'marjanovics@example.com', 'Gunduliceva 14', 'Novi Sad', '061 421 4212', 'ADMINISTRATOR');

INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika, katedra, uloga) VALUES ('Nikola', 'Nikolic', 'nikola', '$2a$12$uxtqKdzyQh8Ve1Vk4xjpXeGPk6W4/R8X/G3dPBrN8Uw0esBrt2jE.', 'nikola@example.com', 'Izmisljenog Heroja 114', 'Novi Sad', '060 230 5232', 'NASTAVNIK', 'Katedra za informatiku', 1);
INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika, katedra, uloga) VALUES ('Luka', 'Matkovic', 'matke', '$2a$12$uxtqKdzyQh8Ve1Vk4xjpXeGPk6W4/R8X/G3dPBrN8Uw0esBrt2jE.', 'matkovic@example.com', 'Brace Jovandic 15', 'Novi Sad', '069 882 7264', 'NASTAVNIK', 'Katedra za informatiku', 1);
INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika, katedra, uloga) VALUES ('Matija', 'Nenadovic', 'matija', '$2a$12$uxtqKdzyQh8Ve1Vk4xjpXeGPk6W4/R8X/G3dPBrN8Uw0esBrt2jE.', 'matija@example.com', 'Micurinova 52', 'Novi Sad', '065 666 7952', 'NASTAVNIK', 'Katedra za informatiku', 0);
INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika, katedra, uloga) VALUES ('Marijana', 'Markov', 'maja', '$2a$12$uxtqKdzyQh8Ve1Vk4xjpXeGPk6W4/R8X/G3dPBrN8Uw0esBrt2jE.', 'majamarkov@example.com', 'Zitni Trg 3', 'Novi Sad', '063 351 9997', 'NASTAVNIK', 'Katedra za informatiku', 0);
INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika, katedra, uloga) VALUES ('Emilija', 'Savkovic', 'ema', '$2a$12$uxtqKdzyQh8Ve1Vk4xjpXeGPk6W4/R8X/G3dPBrN8Uw0esBrt2jE.', 'emilijas@example.com', 'Dositejeva 114', 'Novi Sad', '064 554 6982', 'NASTAVNIK', 'Katedra za informatiku', 2);
INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika, katedra, uloga) VALUES ('Srdjan', 'Ivetic', 'srdja', '$2a$12$uxtqKdzyQh8Ve1Vk4xjpXeGPk6W4/R8X/G3dPBrN8Uw0esBrt2jE.', 'ivetic@example.com', 'Dositejeva 114', 'Novi Sad', '064 554 6982', 'NASTAVNIK', 'Katedra za informatiku', 2);

INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika, jmbg, smer, godina_studija, racun) VALUES ('Sima', 'Simic', 'sima', '$2a$10$APZmkzJfSiMIH0RzO8fb5eOZ0QCe3273LLLDgYzzhJxB7XA5RDPHy', 'simacar@example.com', 'Narodnog Coveka 28', 'Novi Sad', '060 171 7171', 'STUDENT', '2701773305056', 'Softverske i informacione tehnologije', 2, 1500);
INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika, jmbg, smer, godina_studija, racun) VALUES ('Aleksandar', 'Todorovic', 'tosa', '$2a$10$APZmkzJfSiMIH0RzO8fb5eOZ0QCe3273LLLDgYzzhJxB7XA5RDPHy', 'doggo@example.com', 'Narodnog Heroja 28', 'Novi Sad', '060 262 5605', 'STUDENT', '2810998865485', 'Softverske i informacione tehnologije', 2, 13000);
INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika, jmbg, smer, godina_studija, racun) VALUES ('Ivan', 'Gaborov', 'pro', '$2a$10$APZmkzJfSiMIH0RzO8fb5eOZ0QCe3273LLLDgYzzhJxB7XA5RDPHy', 'ivanpro@example.com', 'Narodnog Fronta 225', 'Novi Sad', '060 557 9965', 'STUDENT', '2409996486559', 'Softverske i informacione tehnologije', 2, 2000);
INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika, jmbg, smer, godina_studija, racun) VALUES ('Martina', 'Pavlovic', 'martina', '$2a$10$APZmkzJfSiMIH0RzO8fb5eOZ0QCe3273LLLDgYzzhJxB7XA5RDPHy', 'martina@example.com', 'Jovana Cvijica 28', 'Novi Sad', '062 584 5478', 'STUDENT', '0303994654444', 'Softverske i informacione tehnologije', 2, 0);
INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika, jmbg, smer, godina_studija, racun) VALUES ('Nebojsa', 'Stefanovic', 'nebojsa', '$2a$10$APZmkzJfSiMIH0RzO8fb5eOZ0QCe3273LLLDgYzzhJxB7XA5RDPHy', 'nabojsa@example.com', 'Temerinska 28', 'Novi Sad', '061 335 6777', 'STUDENT', '1212999125566', 'Softverske i informacione tehnologije', 2, 0);
INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika, jmbg, smer, godina_studija, racun) VALUES ('Marko', 'Skakovski', 'skaka', '$2a$10$APZmkzJfSiMIH0RzO8fb5eOZ0QCe3273LLLDgYzzhJxB7XA5RDPHy', 'marko@example.com', 'Branka Radicevica 14', 'Novi Sad', '065 546 3827', 'STUDENT', '0505000454443', 'Softverske i informacione tehnologije', 2, 0);
INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika, jmbg, smer, godina_studija, racun) VALUES ('Kristina', 'Badric', 'kris', '$2a$10$APZmkzJfSiMIH0RzO8fb5eOZ0QCe3273LLLDgYzzhJxB7XA5RDPHy', 'kristina@example.com', 'Ilije Bircanina 17', 'Novi Sad', '065 830 9854', 'STUDENT', '112900098989', 'Softverske i informacione tehnologije', 2, 0);
INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika, jmbg, smer, godina_studija, racun) VALUES ('Marina', 'Milosevic', 'marina', '$2a$10$APZmkzJfSiMIH0RzO8fb5eOZ0QCe3273LLLDgYzzhJxB7XA5RDPHy', 'marina@example.com', 'Koste Racina 28', 'Novi Sad', '061 648 8946', 'STUDENT', '5489788489545', 'Softverske i informacione tehnologije', 2, 0);
INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika, jmbg, smer, godina_studija, racun) VALUES ('Bozidar', 'Sredic', 'boza', '$2a$10$APZmkzJfSiMIH0RzO8fb5eOZ0QCe3273LLLDgYzzhJxB7XA5RDPHy', 'boza@example.com', 'Bulevar Evrope 195', 'Novi Sad', '065 468 9874', 'STUDENT', '2701773305056', 'Softverske i informacione tehnologije', 2, 0);
INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, email, adresa, grad, broj_telefona, tip_korisnika, jmbg, smer, godina_studija, racun) VALUES ('Stevan', 'Bordjoski', 'steva', '$2a$10$APZmkzJfSiMIH0RzO8fb5eOZ0QCe3273LLLDgYzzhJxB7XA5RDPHy', 'steva@example.com', 'Dimitrija Tucovica 77', 'Novi Sad', '066 486 8947', 'STUDENT', '2701773305056', 'Softverske i informacione tehnologije', 2, 0);


INSERT INTO predmet(espb, naziv) VALUES(8, "Osnove programiranja");
INSERT INTO predmet(espb, naziv) VALUES(8, "Objektno programiranje");
INSERT INTO predmet(espb, naziv) VALUES(6, "Matematika");
INSERT INTO predmet(espb, naziv) VALUES(4, "Engleski jezik");
INSERT INTO predmet(espb, naziv) VALUES(5, "Uvod u razvoj softvera");
INSERT INTO predmet(espb, naziv) VALUES(6, "Osnove baza podataka");
INSERT INTO predmet(espb, naziv) VALUES(6, "Platforme za objektno programiranje");
INSERT INTO predmet(espb, naziv) VALUES(6, "Osnove softverskih arhitektura");
INSERT INTO predmet(espb, naziv) VALUES(5, "Programiranje mobilnih sistema i uredjaja");
INSERT INTO predmet(espb, naziv) VALUES(6, "Konfigurisanje i administracija baza podataka");
INSERT INTO predmet(espb, naziv) VALUES(6, "Tehnologije i sistemi eObrazovanja");
INSERT INTO predmet(espb, naziv) VALUES(8, "Poslovna informatika");

INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2021-02-21", "2021-06-05", 1);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2022-02-21", "2022-06-05", 1);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2022-02-21", "2022-06-05", 2);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2021-02-21", "2021-06-05", 2);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2022-02-21", "2022-06-05", 3);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2021-02-21", "2021-06-05", 3);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2021-02-21", "2021-06-05", 4);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2022-02-21", "2022-06-05", 4);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2022-02-21", "2022-06-05", 5);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2021-02-21", "2021-06-05", 5);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2022-02-21", "2022-06-05", 6);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2021-02-21", "2021-06-05", 6);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2021-10-08", "2021-01-13", 7);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2022-10-09", "2022-01-15", 7);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2021-10-08", "2021-01-13", 8);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2022-10-09", "2022-01-15", 8);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2021-10-08", "2021-01-13", 9);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2022-10-09", "2022-01-15", 9);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2021-10-08", "2021-01-13", 10);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2022-10-09", "2022-01-15", 10);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2021-10-08", "2021-01-13", 11);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2022-10-09", "2022-01-15", 11);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2021-10-08", "2021-01-13", 12);
INSERT INTO pohadjanje_predmeta(start_date, end_date, predmet_id) VALUES("2022-10-09", "2022-01-15", 12);
-- 9-18
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(1, 19);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(1, 20);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(1, 11);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(1, 12);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(1, 13);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(2, 14);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(2, 15);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(2, 16);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(2, 17);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(2, 18);

INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(3, 19);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(3, 20);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(3, 11);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(3, 12);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(3, 13);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(4, 14);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(4, 15);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(4, 16);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(4, 17);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(4, 18);

INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(5, 19);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(5, 20);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(5, 11);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(5, 12);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(5, 13);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(6, 14);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(6, 15);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(6, 16);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(6, 17);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(6, 18);

INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(7, 19);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(7, 20);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(7, 11);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(7, 12);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(7, 13);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(8, 14);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(8, 15);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(8, 16);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(8, 17);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(8, 18);

INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(9, 19);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(9, 20);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(9, 11);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(9, 12);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(9, 13);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(10, 14);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(10, 15);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(10, 16);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(10, 17);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(10, 18);

INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(11, 19);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(11, 20);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(11, 11);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(11, 12);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(11, 13);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(12, 14);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(12, 15);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(12, 16);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(12, 17);
INSERT INTO pohadjanje_predmeta_studenti(pohadjanje_predmeta_id, student_id) VALUES(12, 18);

INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(1, 5);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(1, 7);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(1, 9);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(2, 6);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(2, 8);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(2, 10);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(3, 5);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(3, 7);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(4, 6);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(4, 8);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(4, 10);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(5, 5);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(5, 7);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(5, 9);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(6, 6);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(6, 8);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(7, 5);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(7, 7);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(8, 6);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(8, 8);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(8, 10);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(9, 5);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(9, 7);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(9, 9);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(10, 6);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(10, 8);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(11, 5);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(11, 7);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(11, 9);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(12, 6);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(12, 8);
INSERT INTO predavanje_predmeta(predmet_id, nastavnik_id) VALUES(12, 10);


INSERT INTO predispitna_obaveza(tip_testa, predmet_id, datum, sala) VALUES('ISPIT', 1, "2022-07-06", "105");
INSERT INTO predispitna_obaveza(tip_testa, predmet_id, datum, sala) VALUES('KOLOKVIJUM', 2, "2022-07-02", "215");
INSERT INTO predispitna_obaveza(tip_testa, predmet_id, datum, sala) VALUES('PROJEKAT', 3, "2022-07-12", "310");
INSERT INTO predispitna_obaveza(tip_testa, predmet_id, datum, sala) VALUES('ISPIT', 4, "2022-07-11", "105");
INSERT INTO predispitna_obaveza(tip_testa, predmet_id, datum, sala) VALUES('KOLOKVIJUM', 5, "2022-07-02", "215");
INSERT INTO predispitna_obaveza(tip_testa, predmet_id, datum, sala) VALUES('PROJEKAT', 6, "2022-07-05", "310");
INSERT INTO predispitna_obaveza(tip_testa, predmet_id, datum, sala) VALUES('ISPIT', 7, "2021-07-10", "105");
INSERT INTO predispitna_obaveza(tip_testa, predmet_id, datum, sala) VALUES('KOLOKVIJUM', 8, "2021-07-02", "215");
INSERT INTO predispitna_obaveza(tip_testa, predmet_id, datum, sala) VALUES('PROJEKAT', 9, "2021-07-12", "310");
INSERT INTO predispitna_obaveza(tip_testa, predmet_id, datum, sala) VALUES('ISPIT', 10, "2021-07-10", "105");
INSERT INTO predispitna_obaveza(tip_testa, predmet_id, datum, sala) VALUES('PROJEKAT', 11, "2021-07-12", "310");
INSERT INTO predispitna_obaveza(tip_testa, predmet_id, datum, sala) VALUES('KOLOKVIJUM', 12, "2021-07-02", "215");

INSERT INTO dokument(naziv, tip_dokumenta, student_id) VALUES("Neki obrazac za studenta", "OBRAZAC", 11);
INSERT INTO dokument(naziv, tip_dokumenta, student_id) VALUES("Diploma srednje skole", "DIPLOMA", 11);
INSERT INTO dokument(naziv, tip_dokumenta, student_id) VALUES("Popunjeni obrazac", "OBRAZAC", 11);
INSERT INTO dokument(naziv, tip_dokumenta, student_id) VALUES("Diploma za najlegendarnijeg studenta ikada", "DIPLOMA", 12);
INSERT INTO dokument(naziv, tip_dokumenta, student_id) VALUES("Jos jedan obrazac za studenta", "OBRAZAC", 12);

INSERT INTO prijava(ocenjen, polozen, bodovi, predispitna_obaveza_id, student_id) VALUES(false, false, 0, 1, 11);
INSERT INTO prijava(ocenjen, polozen, bodovi, predispitna_obaveza_id, student_id) VALUES(false, false, 0, 2, 11);
INSERT INTO prijava(ocenjen, polozen, bodovi, predispitna_obaveza_id, student_id) VALUES(true, true, 40, 6, 11);

INSERT INTO uplata(datum, iznos, svrha, student_id) VALUES("2022-02-21", 500, "Overa semestra", 11);
INSERT INTO uplata(datum, iznos, svrha, student_id) VALUES("2022-02-22", 1000, "Overa semestra", 11);
INSERT INTO uplata(datum, iznos, svrha, student_id) VALUES("2022-02-22", 5000, "Overa semestra", 12);
INSERT INTO uplata(datum, iznos, svrha, student_id) VALUES("2022-02-22", 8000, "Overa semestra", 12);
INSERT INTO uplata(datum, iznos, svrha, student_id) VALUES("2022-02-22", 2000, "Overa semestra", 13);
